# Generated by Django 5.0.4 on 2024-04-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
